T1_FEATURES_NEW_ALL = [
    'userId_feature', 'itemId_feature', 'UI_count', 'UI_nunique', 'IU_count',
    'IU_nunique', 'UI_count_5core', 'UI_nunique_5core', 'IU_count_5core',
    'IU_nunique_5core', 'user_rating_mean', 'item_rating_mean',
    'train__userId_itemId_emb_0', 'train__userId_itemId_emb_1',
    'train__userId_itemId_emb_2', 'train__userId_itemId_emb_3',
    'train__userId_itemId_emb_4', 'train__userId_itemId_emb_5',
    'train__userId_itemId_emb_6', 'train__userId_itemId_emb_7',
    'train__userId_itemId_emb_8', 'train__userId_itemId_emb_9',
    'train__userId_itemId_emb_10', 'train__userId_itemId_emb_11',
    'train__userId_itemId_emb_12', 'train__userId_itemId_emb_13',
    'train__userId_itemId_emb_14', 'train__userId_itemId_emb_15',
    'train__userId_itemId_emb_16', 'train__userId_itemId_emb_17',
    'train__userId_itemId_emb_18', 'train__userId_itemId_emb_19',
    'train__userId_itemId_emb_20', 'train__userId_itemId_emb_21',
    'train__userId_itemId_emb_22', 'train__userId_itemId_emb_23',
    'train__userId_itemId_emb_24', 'train__userId_itemId_emb_25',
    'train__userId_itemId_emb_26', 'train__userId_itemId_emb_27',
    'train__userId_itemId_emb_28', 'train__userId_itemId_emb_29',
    'train__userId_itemId_emb_30', 'train__userId_itemId_emb_31',
    'train__itemId_userId_emb_0', 'train__itemId_userId_emb_1',
    'train__itemId_userId_emb_2', 'train__itemId_userId_emb_3',
    'train__itemId_userId_emb_4', 'train__itemId_userId_emb_5',
    'train__itemId_userId_emb_6', 'train__itemId_userId_emb_7',
    'train__itemId_userId_emb_8', 'train__itemId_userId_emb_9',
    'train__itemId_userId_emb_10', 'train__itemId_userId_emb_11',
    'train__itemId_userId_emb_12', 'train__itemId_userId_emb_13',
    'train__itemId_userId_emb_14', 'train__itemId_userId_emb_15',
    'train__itemId_userId_emb_16', 'train__itemId_userId_emb_17',
    'train__itemId_userId_emb_18', 'train__itemId_userId_emb_19',
    'train__itemId_userId_emb_20', 'train__itemId_userId_emb_21',
    'train__itemId_userId_emb_22', 'train__itemId_userId_emb_23',
    'train__itemId_userId_emb_24', 'train__itemId_userId_emb_25',
    'train__itemId_userId_emb_26', 'train__itemId_userId_emb_27',
    'train__itemId_userId_emb_28', 'train__itemId_userId_emb_29',
    'train__itemId_userId_emb_30', 'train__itemId_userId_emb_31',
    'train_5core__userId_itemId_emb_0', 'train_5core__userId_itemId_emb_1',
    'train_5core__userId_itemId_emb_2', 'train_5core__userId_itemId_emb_3',
    'train_5core__userId_itemId_emb_4', 'train_5core__userId_itemId_emb_5',
    'train_5core__userId_itemId_emb_6', 'train_5core__userId_itemId_emb_7',
    'train_5core__userId_itemId_emb_8', 'train_5core__userId_itemId_emb_9',
    'train_5core__userId_itemId_emb_10', 'train_5core__userId_itemId_emb_11',
    'train_5core__userId_itemId_emb_12', 'train_5core__userId_itemId_emb_13',
    'train_5core__userId_itemId_emb_14', 'train_5core__userId_itemId_emb_15',
    'train_5core__userId_itemId_emb_16', 'train_5core__userId_itemId_emb_17',
    'train_5core__userId_itemId_emb_18', 'train_5core__userId_itemId_emb_19',
    'train_5core__userId_itemId_emb_20', 'train_5core__userId_itemId_emb_21',
    'train_5core__userId_itemId_emb_22', 'train_5core__userId_itemId_emb_23',
    'train_5core__userId_itemId_emb_24', 'train_5core__userId_itemId_emb_25',
    'train_5core__userId_itemId_emb_26', 'train_5core__userId_itemId_emb_27',
    'train_5core__userId_itemId_emb_28', 'train_5core__userId_itemId_emb_29',
    'train_5core__userId_itemId_emb_30', 'train_5core__userId_itemId_emb_31',
    'train_5core__itemId_userId_emb_0', 'train_5core__itemId_userId_emb_1',
    'train_5core__itemId_userId_emb_2', 'train_5core__itemId_userId_emb_3',
    'train_5core__itemId_userId_emb_4', 'train_5core__itemId_userId_emb_5',
    'train_5core__itemId_userId_emb_6', 'train_5core__itemId_userId_emb_7',
    'train_5core__itemId_userId_emb_8', 'train_5core__itemId_userId_emb_9',
    'train_5core__itemId_userId_emb_10', 'train_5core__itemId_userId_emb_11',
    'train_5core__itemId_userId_emb_12', 'train_5core__itemId_userId_emb_13',
    'train_5core__itemId_userId_emb_14', 'train_5core__itemId_userId_emb_15',
    'train_5core__itemId_userId_emb_16', 'train_5core__itemId_userId_emb_17',
    'train_5core__itemId_userId_emb_18', 'train_5core__itemId_userId_emb_19',
    'train_5core__itemId_userId_emb_20', 'train_5core__itemId_userId_emb_21',
    'train_5core__itemId_userId_emb_22', 'train_5core__itemId_userId_emb_23',
    'train_5core__itemId_userId_emb_24', 'train_5core__itemId_userId_emb_25',
    'train_5core__itemId_userId_emb_26', 'train_5core__itemId_userId_emb_27',
    'train_5core__itemId_userId_emb_28', 'train_5core__itemId_userId_emb_29',
    'train_5core__itemId_userId_emb_30', 'train_5core__itemId_userId_emb_31',
    'simi_scores_mean', 'simi_scores_max', 'simi_scores_min',
    'simi_scores_std', 'simi_scores_sum', 'simi_scores_median',
    'simi_scores_percentile_25', 'simi_scores_percentile_75',
    'simi_scores_percentile_5', 'simi_scores_percentile_95',
    'w2v_word_embedding_0', 'w2v_word_embedding_1', 'w2v_word_embedding_2',
    'w2v_word_embedding_3', 'w2v_word_embedding_4', 'w2v_word_embedding_5',
    'w2v_word_embedding_6', 'w2v_word_embedding_7', 'w2v_word_embedding_8',
    'w2v_word_embedding_9', 'w2v_word_embedding_10', 'w2v_word_embedding_11',
    'w2v_word_embedding_12', 'w2v_word_embedding_13', 'w2v_word_embedding_14',
    'w2v_word_embedding_15', 'w2v_word_embedding_16', 'w2v_word_embedding_17',
    'w2v_word_embedding_18', 'w2v_word_embedding_19', 'w2v_word_embedding_20',
    'w2v_word_embedding_21', 'w2v_word_embedding_22', 'w2v_word_embedding_23',
    'w2v_word_embedding_24', 'w2v_word_embedding_25', 'w2v_word_embedding_26',
    'w2v_word_embedding_27', 'w2v_word_embedding_28', 'w2v_word_embedding_29',
    'w2v_word_embedding_30', 'w2v_word_embedding_31',
    'gcntune1ksubmit_withoutqrel', 'i2ibfssubmit', 'bsl_v2', 'ggcn_t_s0__main',
    'icf_v2__0', 'icf_v3__0', 'icf_v2__1', 'icf_v3__1', 'icf_v2__2',
    'icf_v3__2', 'icf_v2__3', 'icf_v3__3', 'icf_v2__4', 'icf_v3__4',
    'icf_v2__5', 'icf_v3__5', 'icf_v2__6', 'icf_v3__6', 'icf_v2__7',
    'icf_v3__7', 'icf_v2__8', 'icf_v3__8', 'icf_v2__9', 'icf_v3__9'
]

T2_FEATURES_NEW_ALL = [
    'userId_feature', 'itemId_feature', 'UI_count', 'IU_count', 'IU_nunique',
    'UI_count_5core', 'IU_count_5core', 'IU_nunique_5core', 'user_rating_mean',
    'item_rating_mean', 'train__itemId_userId_emb_0',
    'train__itemId_userId_emb_1', 'train__itemId_userId_emb_2',
    'train__itemId_userId_emb_3', 'train__itemId_userId_emb_4',
    'train__itemId_userId_emb_5', 'train__itemId_userId_emb_6',
    'train__itemId_userId_emb_7', 'train__itemId_userId_emb_8',
    'train__itemId_userId_emb_9', 'train__itemId_userId_emb_10',
    'train__itemId_userId_emb_11', 'train__itemId_userId_emb_12',
    'train__itemId_userId_emb_13', 'train__itemId_userId_emb_14',
    'train__itemId_userId_emb_15', 'train__itemId_userId_emb_16',
    'train__itemId_userId_emb_17', 'train__itemId_userId_emb_18',
    'train__itemId_userId_emb_19', 'train__itemId_userId_emb_20',
    'train__itemId_userId_emb_21', 'train__itemId_userId_emb_22',
    'train__itemId_userId_emb_23', 'train__itemId_userId_emb_24',
    'train__itemId_userId_emb_25', 'train__itemId_userId_emb_26',
    'train__itemId_userId_emb_27', 'train__itemId_userId_emb_28',
    'train__itemId_userId_emb_29', 'train__itemId_userId_emb_30',
    'train__itemId_userId_emb_31', 'train_5core__itemId_userId_emb_0',
    'train_5core__itemId_userId_emb_1', 'train_5core__itemId_userId_emb_2',
    'train_5core__itemId_userId_emb_3', 'train_5core__itemId_userId_emb_4',
    'train_5core__itemId_userId_emb_5', 'train_5core__itemId_userId_emb_6',
    'train_5core__itemId_userId_emb_7', 'train_5core__itemId_userId_emb_8',
    'train_5core__itemId_userId_emb_9', 'train_5core__itemId_userId_emb_10',
    'train_5core__itemId_userId_emb_11', 'train_5core__itemId_userId_emb_12',
    'train_5core__itemId_userId_emb_13', 'train_5core__itemId_userId_emb_14',
    'train_5core__itemId_userId_emb_15', 'train_5core__itemId_userId_emb_16',
    'train_5core__itemId_userId_emb_17', 'train_5core__itemId_userId_emb_18',
    'train_5core__itemId_userId_emb_19', 'train_5core__itemId_userId_emb_20',
    'train_5core__itemId_userId_emb_21', 'train_5core__itemId_userId_emb_22',
    'train_5core__itemId_userId_emb_23', 'train_5core__itemId_userId_emb_24',
    'train_5core__itemId_userId_emb_25', 'train_5core__itemId_userId_emb_26',
    'train_5core__itemId_userId_emb_27', 'train_5core__itemId_userId_emb_28',
    'train_5core__itemId_userId_emb_29', 'train_5core__itemId_userId_emb_30',
    'train_5core__itemId_userId_emb_31', 'simi_scores_mean', 'simi_scores_max',
    'simi_scores_min', 'simi_scores_std', 'simi_scores_sum',
    'simi_scores_median', 'simi_scores_percentile_25',
    'simi_scores_percentile_75', 'simi_scores_percentile_5',
    'simi_scores_percentile_95', 'w2v_word_embedding_0',
    'w2v_word_embedding_1', 'w2v_word_embedding_2', 'w2v_word_embedding_3',
    'w2v_word_embedding_4', 'w2v_word_embedding_5', 'w2v_word_embedding_6',
    'w2v_word_embedding_7', 'w2v_word_embedding_8', 'w2v_word_embedding_9',
    'w2v_word_embedding_10', 'w2v_word_embedding_11', 'w2v_word_embedding_12',
    'w2v_word_embedding_13', 'w2v_word_embedding_14', 'w2v_word_embedding_15',
    'w2v_word_embedding_16', 'w2v_word_embedding_17', 'w2v_word_embedding_18',
    'w2v_word_embedding_19', 'w2v_word_embedding_20', 'w2v_word_embedding_21',
    'w2v_word_embedding_22', 'w2v_word_embedding_23', 'w2v_word_embedding_24',
    'w2v_word_embedding_25', 'w2v_word_embedding_26', 'w2v_word_embedding_27',
    'w2v_word_embedding_28', 'w2v_word_embedding_29', 'w2v_word_embedding_30',
    'w2v_word_embedding_31', 'swing_v2_train_only_no_t1t2_cross',
    'swing_v2_train_only_t1t2_cross', 'i2i_bfs_novalid_maxpooling',
    'icf_v2__0', 'icf_v3__0', 'icf_v2__1', 'icf_v3__1', 'icf_v2__2',
    'icf_v3__2', 'icf_v2__3', 'icf_v3__3', 'icf_v2__4', 'icf_v3__4',
    'icf_v2__5', 'icf_v3__5', 'icf_v2__6', 'icf_v3__6', 'icf_v2__7',
    'icf_v3__7', 'icf_v2__8', 'icf_v3__8', 'icf_v2__9', 'icf_v3__9',
    'ggcn_t_s0', 'ggcn_t_s1', 'ggcn_t_s1s2', 'ggcn_t_s1s2s3', 'ggcn_t_s1s3',
    'ggcn_t_s2', 'ggcn_t_s2s3', 'ggcn_t_s3'
]
